/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable sort-imports-es6-autofix/sort-imports-es6 */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 door_handle.glb -t 
Author: Helindu (https://sketchfab.com/Helindu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/door-handle-b17802a127954b868a1250f55597142d
Title: Door Handle
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    door_handle_Handle_material001_0: THREE.Mesh
  }
  materials: {
    ['Handle_material.001']: THREE.MeshStandardMaterial
  }
}

interface DoubleDoorHandlePropsType {
  scale: [number, number, number]
  position: [number, number, number]
  rotation: [number, number, number]
}

export function DoubleDoorHandle({ scale, position, rotation }: DoubleDoorHandlePropsType) {
  const { nodes, materials } = useGLTF('/assets/models/door_handle.glb') as GLTFResult
  return (
    <group
      castShadow
      receiveShadow
      scale={scale}
      position={position}
      rotation={rotation}
      dispose={null}>
      <mesh
        geometry={nodes.door_handle_Handle_material001_0.geometry}
        material={materials['Handle_material.001']}
        position={[-1.322, 0, -0.5]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={595.617}
      />
    </group>
  )
}

useGLTF.preload('/assets/models/door_handle.glb')
